### ISSUE TITLE
Support for cross-platform clipboard

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1938]
Right now clipboard support (copy, paste etc) is only supported in the Windows platform, and for Linux and macOS the feature is simply disabled. This is certainly not the ideal behaviour, and I have heard some Linux user would like to see clipboard support, so I hope there exists a light-weighted cross-platform so that cross-platform clipboard support can be added for DOSBox-X, not just on Windows.

**Comment by joncampbell123** [comment]
Not sure yet about Mac OS X, but Linux/X11 support could be done at the Xlib X11 protocol level.

https://www.uninformativ.de/blog/postings/2017-04-02/0/POSTING-en.html

**Comment by joncampbell123** [comment]
Ah, I think this is Mac OS X's clipboard API.

https://developer.apple.com/documentation/appkit/nspasteboard

**Comment by Wengier** [comment]
@joncampbell123 Thanks. I will try the Linux/X11 code, but I think the Mac OS X's clipboard API is Objective C only (not C++). I hope to get it work at least in Linux, but it will be the best if there is a solution for all supported platforms of course.

**Comment by joncampbell123** [comment]
There are parts of DOSBox-X that are Objective C++. I've had no problem compiling .mm files as part of the project on Mac OS X. The NSMenu support code in ./src/gui/menu_osx.mm for example.

**Comment by Wengier** [comment]
@joncampbell123 I have tried the X11 code, which seems to be able to get X11's clipboard text properly. However, setting X11's clipboard text is more problematic, and I kept getting "Denying request of type xxx" with the code even if it builds fine. I have also tried to change the code somewhat, but I was not able to get this to work as desired, partly because I am not particularly familiar with the X11 protocol.

Meanwhile, I have also tried libclipboard (https://github.com/jtanx/libclipboard), a lightweight cross-platform clipboard library, which seems to work fine in Windows (both copy and paste), but the code seems to freeze with Linux/X11. I have checked there are multiple places in the code that can cause freezes in the X11 code, so I had to discard it for now.

**Comment by rderooy** [comment]
@Wengier just a thought... are you actually running X11 or are you running Wayland? I suspect the later. X11 has a sort of free-for-all model where any X11 app can access anything, while wayland introduces a security model. You may be running into the later, even though Xwayland (under which dosbox-x should be running) has a more relaxed security model.

To test if this is the case, at the graphical login screen when you select your user, there should be a little gear icon. Press this and select something like "Gnome on X11", and try again. Not that this is a solution obviously.

**Comment by Wengier** [comment]
@rderooy I simply used the preprocessor ```#if defined(LINUX) and C_X11``` to check if it is Linux/X11 in the code. But as I primarily use Windows, you are certainly more familiar with Linux than me. 

I wonder where I can find the little gear icon at the graphical login screen? I have not found it for now, so could you post a screenshot showing it? Thanks!

**Comment by rderooy** [comment]
@Wengier they changed the location of the icon at some point. I think you said you where running Fedora 31, which I think had it just underneath the Password input field, next to the sign in button. In Fedora 33, it is in the bottom right corner of the screen.

Once you find the gear icon, select "GNOME on Xorg".

Again, you will not see the gear icon if you have not yet selected the user to login as. Also you will not see it on the lock screen, you need to be at the login screen.

old location:
https://tracker.pureos.net/file/data/ilr4x43gc4ctz6e67nny/PHID-FILE-uv33u5fu7v64hbttxl3u/GDM-screenshot.png

**Comment by rderooy** [comment]
Also note that the option is "sticky", so it will remember the last option you last chose on subsequent logins.

**Comment by Wengier** [comment]
@rderooy Yes you are right, I can find "GNOME on Xorg" only at the login screen, but not the lock screen.

**Comment by Wengier** [comment]
@rderooy Nevertheless, the result I got when logged in as "GNOME on Xorg" seems to be the same as before. Instead of successfully setting the X11 clipboard with the code, I continue to get messages likes this:

```
Requestor: 0x2400002
Denying request of type 'TARGETS'
```

**Comment by Wengier** [comment]
Maybe the sample code itself has issues. If there is other code there may work with Linux clipboard please let me know as well. Also, I do not have macOS here so I am not able to test the macOS clipboard code myself.

**Comment by rderooy** [comment]
Not sure if this helps...
Another emulator that uses SDL2 has recently implemented copy and paste functionality. openMSX, the emulator for an 80's home computer system popular in Japan and to some extend Europe.

Here is a commit where they implement paste functionality using SDL2.
https://github.com/openMSX/openMSX/commit/9bdf1d2383e83b1858aa926e5fc70893d8d65a96

**Comment by Wengier** [comment]
@rderooy Thanks for the link. Yes, it will work! However this will make the Linux (and likely also macOS) clipboard feature SDL2 only.

**Comment by Wengier** [comment]
@rderooy The mouse copy/paste feature is now available for non-Windows systems on SDL2 builds, and pasting from the clipboard is also available for the Linux/X11 systems on SDL1 builds (https://github.com/joncampbell123/dosbox-x/commit/f4a58b12c8984e7959e92cfae926b061632d4f4a). On the other hand, the clipboard device (CLIP$) and DOS clipboard API are currently still Windows-only.

**Comment by rderooy** [comment]
@Wengier I know that the SDL2 feature would obviously preclude SDL1. But on the other hand, it should be cross-platform and work on Linux, Windows and macOS. And hopefully it is also compatible with Wayland, once the SDL lack-of-window-decoration-on-wayland issue is sorted upstream.

Generally, I think it would be a good idea to start to default to SDL2. And only promote the SDL1 builds for legacy platforms that cannot support SDL2. Are there any features left that are SDL1 only, after SDLNet got sorted?

**Comment by Wengier** [comment]
I agree with the general idea to make SDL2 the preferred build, but apparently @joncampbell123 knows more about the details of the differences between SDL1 and SDL2 builds. Perhaps there should be a Wiki page to explain the differences between them to let the end-users know how to choose between them.

**Comment by joncampbell123** [comment]
SDL2 builds use the stock SDL2 library code since that is an actively developed project.

SDL1 builds use a version that I have heavily modified since SDL1 is apparently deprecated. However my heavy modifications allow for many extensions to work, including Win32 language ID, menus, asynchronous window resizing (meaning that moving and resizing the window doesn't pause emulation), alterations for @yksoft1 for HX DOS builds, Apple touch bar support, etc. Those alterations cannot be done to SDL2 builds without modifying SDL2 heavily as well, which is a bad idea considering that fixes and upgrades may be obtained by just updating the SDL2 library from the main site.

**Comment by Wengier** [comment]
@joncampbell123 It is true that the SDL1 build has things that work differently in SDL2 build when you mention the extensions, most notably the menu system in Windows SDL1 builds. I think right now this one is still preferred over the menu system in Windows SDL2 builds, which use SDL custom drawn menu system. For example, when you use the GLSL shader in OpenGL output, the menu bar will disappear in Windows SDL2 builds, but not in Windows SDL1 builds, so it does have its apparent advantages. I hope to create a Wiki page shortly to explain to users about the differences between them and how to choose between them.

**Comment by Wengier** [comment]
@joncampbell123 By the way, speaking of the SDL drawn menu issue, if you know how to make the GLSL shaders work with the SDL drawn menu (Issue #1887), please let me know. Thanks!

**Comment by joncampbell123** [comment]
@Wengier I'm aware that SDL2 opens up the ability to use and allocate OpenGL contexts, so perhaps the menus should have their own OpenGL context separate from the DOS screen and it's shader. I'm not entirely sure if the two contexts could coexist on the same window though.

**Comment by joncampbell123** [comment]
https://wiki.libsdl.org/SDL_GL_CreateContext

**Comment by joncampbell123** [comment]
If they could, great. Otherwise, it's a potential mess of code much like how SDL1 has to delicately manage the OpenGL context when sharing it with 3Dfx emulation. It's so delicate that the window has to prevent you from resizing it while 3Dfx OpenGL emulation is active.

**Comment by Carpintonto** [comment]
Having an impasse here on Ubuntu 18.04.5.

I just got v0.83.7, Linux SDL2, 64-bit to compile this afternoon, but at runtime it complained:
dosbox-x: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
and the same for libavformat.so.58, libavutil.so.56, libswscale.so.5, libswresample.so.3, and libfdk-aac.so.2

Each time I located and copied the missing shared libraries in the snap installation until it ran
sudo cp /snap/dosbox-x/597/usr/lib/libswresample.so.* /usr/lib/x86_64-linux-gnu

Now with whatever I cloned at around 11:30pm  PDT

build-debug-sdl2
-rw-rw-r-- 1 john john 23 Oct 13 00:16 stamp-h1

I see a lot of 
//usr/lib/x86_64-linux-gnu/libavcodec.so.57: undefined reference to ...

I tried with and without the shared libraries I copied from the /snap/dosbox-x/597/usr/lib/ to /usr/lib/x86_64-linux-gnu

Attached find config.log and the end of the console output

[config.log](https://github.com/joncampbell123/dosbox-x/files/5369774/config.log)
[console_tail.txt](https://github.com/joncampbell123/dosbox-x/files/5369778/console_tail.txt)

**Comment by Wengier** [comment]
@Carpintonto I think you seem to have issue with the avcodec. Perhaps you can try disable this feature if you do not really need it:

configure --disable-avcodec

**Comment by Wengier** [comment]
@joncampbell123 Looks like it is kind of problematic to make the GLSL shaders work with the SDL drawn menu. So far I have not yet found references to make two OpenGL contexts coexist on the same window.

**Comment by Carpintonto** [comment]
@Wengier I think I understand you to mean run 

./configure --disable-avcodec
and then
./build-debug-sdl2

No discernible change - still throwing 
//usr/lib/x86_64-linux-gnu/libavcodec.so.57: undefined reference to ....

and interestingly, even when it does compile, 
grep error config.log | wc -l
always returns 47.

My healthy boundary on this project is to NOT edit any code.

I'm glad to try suggestions, move files around, and report back so the team can get a sense of what's happening and not on Ubuntu 18.04.5.  <-- for what it's worth; I'm getting the suggestions to upgrade the distro so my help may be of limited applicability until I do.

**Comment by Wengier** [comment]
@Carpintonto No, if you run ./build-debug-sdl2 after ./configure --disable-avcodec then the configure option will be overridden and has no effect. Try run ./configure --disable-avcodec and then “make” instead.

**Comment by Wengier** [comment]
@Carpintonto These are just warnings which you can ignore.

The actual error seems to be about the SDL1. Make sure you build for SDL2 instead of SDL1 since you want the SDL2 build.

./build-debug-sdl2
Stop after avcodec errors, then:
./configure --disable-avcodec
make

**Comment by Carpintonto** [comment]
@Wengier still not happening.  I really want to paste in from the clipboard to report success.  I also do other things!  Maybe you try qemu hosting Ubuntu?

**Comment by Wengier** [comment]
@rderooy is more familiar with Linux stuff than me (since I am a Windows user). He can probably help you in this case.

**Comment by Carpintonto** [comment]
@Wengier - I'm trying to help YOU.  If I NEED to paste from a DOS emulator, I already can

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.
 
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Kernel: allocated 115 Diskbuffers = 62560 Bytes in HMA
Process 0 starting: F:\command.com /e:384 /k %FDPP_AUTOEXEC%
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20201004-2355-gc2590dee5
 
C:\>

**Comment by Wengier** [comment]
@Carpintonto Sure I would like to see DOSBox-X's clipboard working in Linux, and I appreciate any help for that. But if I understand it correctly, the issue you currently encounter is with the code building in Linux (Ubuntu), right? And the code that prevents it from building correctly on your system is clearly not the clipboard code, but something else (avcodec etc which has nothing to do the clipboard). Since @rderooy is more familar with the Linux system in general, I hope he could help you to solve the Linux building issue. And after that we can start to discuss the actual clipboard function for Linux in DOSBox-X. Thanks for your support.

**Comment by Carpintonto** [comment]
@Wengier 
I got v0.83.7, Linux SDL2, 64-bit to compile yesterday afternoon, but at runtime it complained:
dosbox-x: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
and the same for libavformat.so.58, libavutil.so.56, libswscale.so.5, libswresample.so.3, and libfdk-aac.so.2

Each time I located and copied the missing shared libraries in the snap installation until it ran
sudo cp /snap/dosbox-x/597/usr/lib/libswresample.so.* /usr/lib/x86_64-linux-gnu

and it's running right now- I'll watch for a release.

**Comment by Wengier** [comment]
@Carpintonto So you meant you have already managed to get DOSBox-X SDL2 working in your Linux system? Great if this is the case. If DOSBox-X is already running right now, have you tried the mouse clipboard copy/paste feature already? For example, under "Main" menu there is a "Shared clipboard function" menu group; you can enable "Quick Edit" and then select, copy or paste text using the mouse button. Let me know if you find any issues with the feature. Thanks!

**Comment by rderooy** [comment]
@Carpintonto looking at https://packages.ubuntu.com/search?keywords=libavformat I notice something weird. You say your running 18.04. Yet libavcodec.58 is from ubuntu 20.04. That is why you don't find the libraries. The binary was compiled for a newer Ubuntu release. So either upgrade to Ubuntu 20.08, or compile it on Ubuntu 18.04 with the libraries and header files from that release.

**Comment by Wengier** [comment]
@Carpintonto I think it may be a coincidence, but the errors when you built with the newer code are indeed unrelated to the clipboard feature. There are multiple code improvements made in the past 24 hours (only some of them were made by me), and the build issue you may have encountered on your Linux system must be caused by something else.

**Comment by Carpintonto** [comment]
@rderooy  thank you Robert - that's some enlightenment

@Wengier I refer you back to https://github.com/joncampbell123/dosbox-x/issues/1938#issuecomment-707561388

re-read what I said.  That's the version still running.  Whatever you have done since that commit has broken all efforts I've made since 11:30 pm last night on my 18.04.5

I am not going to upgrade my distro just to see IF I can compile the latest from a cross-development effort attempted on Windows.

Read this whole thread - seems like everybody's waiting to talk and nobody's listening- 
it's like Abbott and Costello's Who's on First.

It has been entertaining.  Cheers!

**Comment by Wengier** [comment]
@Carpintonto Yes, I have already got what you meant - you meant that the code before last night did build but showing missing shared libraries, which can be solved after some efforts. On the other hand, the code after 11:30 pm last night does not build due to the avcodec errors etc. This is correct, right?

HOWEVER, as I have already mentioned in https://github.com/joncampbell123/dosbox-x/issues/1938#issuecomment-707962702 the errors with the newer code are indeed unrelated to the clipboard feature. I have also mentioned in that comment that I was not the only one who has made commit since that time, and in fact I did not change anything related the avcodec feature recently (actually *never*). I do not know who has modified the code related to the avcodec feature recently, but it should be clear it was not me.

**Comment by Carpintonto** [comment]
nor I !

**Comment by Wengier** [comment]
The most important thing is not to find out who modified the code I think, but to fix it when a problem is found. Thanks for reporting this so that we can try to check the problem.

**Comment by Wengier** [comment]
@rderooy Could you please check what may be wrong with the recent code (related to avcodec) that may cause the issue that @Carpintonto encountered? You are surely a Linux expert.

**Comment by rderooy** [comment]
@Wengier I will try to find a moment tomorrow.

**Comment by rderooy** [comment]
A few things. DOSBox-X as mentioned uses a custom SDL1 build. I found that sometimes with a clean tree, in particular with the flatpak build, I first needed to build SDL1. As such give this a try for SDL1:

```
cd vs2015/sdl
./build-dosbox.sh
cd ../..
./build-debug --disable-avcodec
```

Regarding avcodec. with ``ldd`` you can check against which external libs a binary is linked.

Here is a SDL1 build result, looking for AV
```
$ ldd dosbox-x |grep -i av
	libavcodec.so.58 => /lib64/libavcodec.so.58 (0x00007f7924661000)
	libavformat.so.58 => /lib64/libavformat.so.58 (0x00007f7924412000)
	libavutil.so.56 => /lib64/libavutil.so.56 (0x00007f792416e000)
	libdav1d.so.4 => /lib64/libdav1d.so.4 (0x00007f7923393000)
	librav1e.so.0 => /lib64/librav1e.so.0 (0x00007f7921fd4000)
```
As you can see, it is linked against avcodec.

Here is another SDL1 build, this time compiled with --disable-avcodec:
```
$ ldd dosbox-x|grep -i av
```
As you can see, it returns nothing. So it is NOT linked against avcodec.

I also tried the same thing with SDL2, and the same thing applies when checking with ``ldd``.

Note: running ``--disable-avcodec`` against ``./configure`` is pointless if afterwards you run a script like ``build-debug``, since the build scripts will just run configure again, which will re-enable it. So you want to just skip running ``configure`` and just directly run the build script, but with the ``-disable-avcodec`` parameter as I show above.

**Comment by Wengier** [comment]
@rderooy So you think the avcodec feature in DOSBox-X always behaves like this, i.e. there is no regression in the recent code that may cause building issue with avcodec in Linux?

**Comment by rderooy** [comment]
@Wengier I would not say there are no regressions. As you may recall I had created a bug report that win9x crashes on startup after enabling avcodec (that got subsequently overrun by someone posting unrelated issues), and that I just closed. Those crashes still happen. But they are not related to any change to the code itself, but simply to the config system. With the old detection method avcodec simply did not get enabled on my system as it never found the libraries, with the new one it does find the libs and enables it and crashes on starting windows.

**Comment by Wengier** [comment]
@rderooy It looks like @Carpintonto is unable to build the latest code successfully in Linux due to the avcodec stuff. Do you have for example a Linux Flatpak build for the latest code that can be used to demonstrate the Linux clipboard feature to @Carpintonto?

**Comment by rderooy** [comment]
@Wengier There is no point in me providing a binary, since it will have the same problem as the snap version he seems to be using now. Namely that it is compiled against newer libs.

For the flatpak, the flathub repository is only for tagged release versions. Which means waiting another 2 weeks.

It is possible for nightly flatpaks to be hosted on your own webserver. Perhaps this could be done on dosbox-x.com
There is some docs for hosting your own repository here: https://docs.flatpak.org/en/latest/hosting-a-repository.html
But I have not tried this, but I think you can just run the ``build-flatpak-sdl2.sh`` script and put the resulting "myrepo" repository directory that is created onto the web server. Perhaps just rename "myrepo" to something else in the build script :-)

**Comment by Wengier** [comment]
@rderooy Have you checked the clipboard feature yourself on Linux then? Does it work properly for you?

**Comment by rderooy** [comment]
To be honest, I had not yet gotten around to trying it. Been busy with other stuff for the last week or so.

I just gave it a quick try. First this seems to be exclusive to SDL2 for now right?

- I was able to do some simple paste operations into dosbox-x SDL2 with shift+right-mouse button.
- I was also able to select text in dosbox-x and paste it outside dosbox-x into a text editor.

What I was not able to copy out of dosbox-x was the border characters used for the dosbox-x intro screen. If I select any of those box (border drawing) characters, paste did not do anything. So perhaps it only works for the lower ascii characters? Also taking into account that the on-screen characters can vary depending on codepage used. But all the characters should exist in unicode, even those box drawing characters.

**Comment by joncampbell123** [comment]
@rderooy The code page conversion code currently used for filenames could be used for converting to/from unicode on the clipboard.

**Comment by Wengier** [comment]
@joncampbell123 Thanks for the hint. I have implemented UTF-8 to ASCII conversion using the conversion code.

@rderooy Please check out the latest code and see how the border characters work when pasting. Thanks!

**Comment by Wengier** [comment]
@rderooy Also, mouse copy/paste feature is specific to SDL2 builds indeed, but pasting from the clipboard feature (mappable from the mapper editor) is available for SDL1 builds too. For Linux SDL2 builds there is a "Shared clipboard functions" menu group (under "Main") as in the Windows builds.

**Comment by Wengier** [comment]
As for the avcodec, as I said in the newly-opened Issue #1947, it could be disabled by default in some way until the problem is solved.

**Comment by rderooy** [comment]
@Wengier I can paste into dosbox-x *some* individual box characters, but try to paste this:
As I said, some individual characters are fine, but as a group it just ends up as junk.

```
U+250x ─ ━ │ ┃ ┄ ┅ ┆ ┇	┈ ┉ ┊ ┋ ┌ ┍ ┎ ┏
U+251x ┐ ┑ ┒ ┓ └ ┕ ┖ ┗	┘ ┙ ┚ ┛ ├ ┝ ┞ ┟
U+252x ┠ ┡ ┢ ┣ ┤ ┥ ┦ ┧	┨ ┩ ┪ ┫ ┬ ┭ ┮ ┯
U+253x ┰ ┱ ┲ ┳ ┴ ┵ ┶ ┷	┸ ┹ ┺ ┻ ┼ ┽ ┾ ┿
U+254x ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇	╈ ╉ ╊ ╋ ╌ ╍ ╎ ╏
U+255x ═ ║ ╒ ╓ ╔ ╕ ╖ ╗ ╘ ╙ ╚ ╛ ╜ ╝ ╞ ╟
U+256x ╠ ╡ ╢ ╣ ╤ ╥ ╦ ╧ ╨ ╩ ╪ ╫ ╬ ╭ ╮ ╯
U+257x ╰ ╱ ╲ ╳ ╴ ╵ ╶ ╷	╸ ╹ ╺ ╻ ╼ ╽ ╾ ╿

U+258x ▀ ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
U+259x ▐ ░ ▒ ▓ ▔ ▕ ▖ ▗ ▘ ▙ ▚ ▛ ▜ ▝ ▞ ▟
```
This comes from: https://en.wikipedia.org/wiki/Box-drawing_character and I cleaned it up a bit by removing the tab characters by spaces, in case the tabs where causing problems.

Also, I still cannot copy box drawing characters out-of dosbox-x.

**Comment by rderooy** [comment]
This is pasted line-by-line as newline seems to be ignored when pasting and it becomes an even bigger mess.
![edit_001](https://user-images.githubusercontent.com/17701098/96232898-63476100-0f98-11eb-9256-60833a512326.png)

**Comment by rderooy** [comment]
Also regarding the SDL1 build, the "Shared clipboard functions" menu is missing, and shift + right-mouse-button does nothing.

**Comment by Wengier** [comment]
@rderooy I will check that out. Meanwhile, for Linux SDL1 build, the only available function is the Paste Clipboard function, mappable from the key mapper, so I don't think adding such as menu group is really useful for this build.

**Comment by Wengier** [comment]
@rderooy For Linux SDL1 build, I have decided to add a single menu item "Paste from the Clipboard" under the Main menu in the latest code, instead of the "Shared clipboard functions" menu group.

**Comment by Wengier** [comment]
@rderooy I have improved the pasting for box characters in the latest code. It appears that I had to do some checks myself. Basically it can still paste characters supported by the current codepage in DOSBox-X, but it will hopefully no longer paste junks as before. Please check it out.

**Comment by rderooy** [comment]
@Wengier 

**Improvements**
- when pasting works, I get more characters than before.

**no change**
- pasting linefeed is still ignored (Linux/Unix produces no Carriage Return (CR), unlike DOS/Windows).
- pasting tab causes beeps, and produces no tab

**regression**
- paste option is gone from the menu

I say when pasting works, because I found that trying to use the paste function with the mouse, when the mouse is active in dosbox-x, such as simply loading ``edit``, does not work most of the time. And on the rare occasion that it does something, what you get is not correct. I used the paste option from the menu yesterday to get that screenshot, but the paste option is now gone.
Pasting with the mouse at the DOS prompt works better, since no mouse emulation is active at that point.

**Comment by Wengier** [comment]
@rderooy The paste menu option was added to the Linux SDL1 build. When I did this, I accidently hid it from the Linux SDL2 build. I have already restored it for Linux SDL1 build. So please check out the latest code. (But please note that even if it was not shown from the menu, it could still be accessed with the shortcut defined in the key mapper).

Also, I decided to convert tabs to 4 spaces in the latest code. As for the linefeed, I think it was deliberately ignored so that the pasting looks better from the DOS shell. If this causes issue(s) please let me know. Thanks!

**Comment by Wengier** [comment]
@rderooy As for mouse issue you mentioned, I think pasting it in ```edit``` does work here, although not at times apparently because of the interferes from the mouse emulation. In such cases I would suggest you to use the menu option for pasting instead, which should by now be available for both Linux SDL1 and SDL2 builds.

**Comment by rderooy** [comment]
@Wengier Thanks!

I can confirm that the paste menu option is now available and works in both SDL1 and SDL2 builds.

Here is the current state when pasting line-by-line in the SDL2 build:
![edit_000](https://user-images.githubusercontent.com/17701098/96363047-15fef700-1132-11eb-935e-f3f13286be73.png)

I still think that ignoring the newline is not the right thing to do. I cannot think of any other place that newline is ignored.

**Comment by rderooy** [comment]
Here is codepage 437

```
   0 1 2 3 4 5 6 7 8 9 A B C D E F

0    ☺ ☻ ♥ ♦ ♣ ♠ • ◘ ○ ◙ ♂ ♀ ♪ ♫ ☼
1  ► ◄ ↕ ‼ ¶ § ▬ ↨ ↑ ↓ → ← ∟ ↔ ▲ ▼
2    ! " # $ % & ' ( ) * + , - . /
3  0 1 2 3 4 5 6 7 8 9 : ; < = > ?
4  @ A B C D E F G H I J K L M N O
5  P Q R S T U V W X Y Z [ \ ] ^ _
6  ` a b c d e f g h i j k l m n o
7  p q r s t u v w x y z { | } ~ ⌂
8  Ç ü é â ä à å ç ê ë è ï î ì Ä Å
9  É æ Æ ô ö ò û ù ÿ Ö Ü ¢ £ ¥ ₧ ƒ
A  á í ó ú ñ Ñ ª º ¿ ⌐ ¬ ½ ¼ ¡ « »
B  ░ ▒ ▓ │ ┤ ╡ ╢ ╖ ╕ ╣ ║ ╗ ╝ ╜ ╛ ┐
C  └ ┴ ┬ ├ ─ ┼ ╞ ╟ ╚ ╔ ╩ ╦ ╠ ═ ╬ ╧
D  ╨ ╤ ╥ ╙ ╘ ╒ ╓ ╫ ╪ ┘ ┌ █ ▄ ▌ ▐ ▀
E  α ß Γ π Σ σ µ τ Φ Θ Ω δ ∞ φ ε ∩
F  ≡ ± ≥ ≤ ⌠ ⌡ ÷ ≈ ° ∙ · √ ⁿ ² ■
```

And here it is pasted line-by-line. Some characters are missing, or cause edit to open search of file menus. Also sometimes even spaces in between the characters are missing. Pasting too fast perhaps and overrunning the keyboard buffer?

![edit_001](https://user-images.githubusercontent.com/17701098/96363598-b7d41300-1135-11eb-93ba-c9c8c46d1f8a.png)

**Comment by Wengier** [comment]
@rderooy I think the code was trying to ignore LF and will accept CR, but it appears that it did not work well as you said. So I have already fixed this. Please check out the latest code.

As for missing characters when pasting as a group, I believe they are caused by the pasting speed indeed. The pasting speed can be set with the clip_paste_speed config option, which defaulted to 20. I have now increased it to 30 by default so that the speed should be somewhat slower. Please check it out as well.

Thanks for testing and please let me know how the new code works.

**Comment by Wengier** [comment]
@rderooy Have you checked it out yet?

**Comment by rderooy** [comment]
@Wengier Yes, just did not have the time to comment. With the new timing, pasting works better but not perfect. I did find that increasing the emulated CPU speed does allow a larger paste to succeed. So perhaps the paste speed should be proportional to the emulated CPU speed.

Also, some characters are interpreted as control characters. But I guess that is to be expected...
- 06 is interpreted as CTRL-+ (Find in Edit)
- 08 is interpreted as a backspace
- 09 is interpreted as a tab (8 spaces in Edit)
- 0A is interpreted as a newline
- 0D is interpreted as a newline
- 0E is interpreted as CTRL-N (New in Edit)
- 0F is interpreted as CTRL-O (Open in Edit)
- 10 has no visual effect in Edit
- 13 is interpreted as CTRL-S (Save in Edit)
- 17 does paste, but vanishes when you do edits on the same line
- 1B has no visual effect in Edit
- 7F has no visual effect in Edit

![edit_002](https://user-images.githubusercontent.com/17701098/96555093-a0bd2e80-12b7-11eb-82ef-053fabd01e0c.png)

**Comment by rderooy** [comment]
Selecting the above table in DOSBox-X and pasting it on the host gives me this:
```
   0 1 2 3 4 5 6 7 8 9 A B C D E F

0                   
1                    
2    ! " # $ % & ' ( ) * + , - . /
3  0 1 2 3 4 5 6 7 8 9 : ; < = > ?
4  @ A B C D E F G H I J K L M N O
5  P Q R S T U V W X Y Z [ \ ] ^ _
6  ` a b c d e f g h i j k l m n o
7  p q r s t u v w x y z { | } ~
8  � � � � � � � � � � � � � � � �
9  � � � � � � � � � � � � � � � �
A  � � � � � � � � � � � � � � � �
B  � � � � � � � � � � � � � � � �
C  � � � � � � � � � � � � � � � �
D  � � � � � � � � � � � � � � � �
E  � � � � � � � � � � � � � � � �
F  � � � � � � � � � � � � � � �
```

**Comment by Wengier** [comment]
@rderooy I am not sure exactly how the clipboard paste speed should be proportional to the emulated CPU speed, as different pasting speed may be needed for different programs anyway. Meanwhile, you can always manually adjust the pasting speed with that option.

On the other hand, you are right that code page conversion should be done for Linux clipboard copy as well, not just Linux clipboard paste. I have already improved the Linux clipboard copy function in the latest code (https://github.com/joncampbell123/dosbox-x/commit/062d134d03765426597d4c5b394c7770eebc4268). Please check it out and see how it works. Thanks.

**Comment by rderooy** [comment]
@Wengier 

Something weird is going on. When I use the right-mouse copy function, and copy it into a web browser input field like this, there is no change:
```
   0 1 2 3 4 5 6 7 8 9 A B C D E F

0                   
1                     
2    ! " # $ % & ' ( ) * + , - . /
3  0 1 2 3 4 5 6 7 8 9 : ; < = > ?
4  @ A B C D E F G H I J K L M N O
5  P Q R S T U V W X Y Z [ \ ] ^ _
6  ` a b c d e f g h i j k l m n o
7  p q r s t u v w x y z { | } ~
8  � � � � � � � � � � � � � � � �
9  � � � � � � � � � � � � � � � �
A  � � � � � � � � � � � � � � � �
B  � � � � � � � � � � � � � � � �
C  � � � � � � � � � � � � � � � �
D  � � � � � � � � � � � � � � � �
E  � � � � � � � � � � � � � � � �
F  � � � � � � � � � � � � � � �
```
When I open a text editor, and try to paste, it pastes literally nothing. When I start the editor (gedit) from a terminal, it prints the following message when I paste:
``(gedit:31455): Gdk-WARNING **: 10:59:03.252: Error converting selection from UTF8_STRING``

I also sometimes get this error:
``(gedit:33594): Gtk-WARNING **: 11:16:46.698: Error converting from text/plain;charset=utf-8 to UTF-8: invalid UTF-8``

But when I paste the copied text back into dosbox-x (even after closing and restarting it), it pastes just fine.

Here is an example of what I get when trying to examine the clipboard contents. This is with the first 2 rows missing from the data copied to avoid the control characters:
```
$ xclip -o -t TARGETS -selection clipboard
TARGETS
UTF8_STRING
$ xclip -o -t UTF8_STRING -selection clipboard
F  � � � � � � � � � � � � � � �
```

But sometimes, I get more TARGETS for some reason.
```
$ xclip -o -t TARGETS -selection clipboard
text/plain
text/plain;charset=utf-8
STRING
TEXT
COMPOUND_TEXT
UTF8_STRING
TARGETS
TIMESTAMP
$ xclip -o -t UTF8_STRING -selection clipboard
(gedit:33594): Gtk-WARNING **: 11:16:46.698: Error converting from text/plain;charset=utf-8 to UTF-8: invalid UTF-8
$ xclip -o -t STRING -selection clipboard
(gedit:33594): Gtk-WARNING **: 11:16:46.698: Error converting from text/plain;charset=utf-8 to UTF-8: invalid UTF-8
$ xclip -o -t STRING -selection clipboard UTF8_                         ^C
$ xclip -o -t text/plain -selection clipboard
(gedit:33594): Gtk-WARNING **: 11:16:46.698: Error converting from text/plain;charset=utf-8 to UTF-8: invalid UTF-8
```

**Comment by Wengier** [comment]
@rderooy This is the result I got when I copied the content from the DOSBox-X window (Linux SDL2) and then pasted here:

  +---------------------------------+
0 |       0 @ P ` p Ç É á ░ └ ╨ α ≡ |
1 |     ! 1 A Q a q ü æ í ▒ ┴ ╤ ß ± |
2 |     " 2 B R b r é Æ ó ▓ ┬ ╥ Γ ≥ |
3 |     # 3 C S c s â ô ú │ ├ ╙ π ≤ |
4 |     $ 4 D T d t ä ö ñ ┤ ─ ╘ Σ ⌠ |
5 |     % 5 E U e u à ò Ñ ╡ ┼ ╒ σ ⌡ |
6 |     & 6 F V f v å û ª ╢ ╞ ╓ µ ÷ |
7 |     ' 7 G W g w ç ù º ╖ ╟ ╫ τ ≈ |
8 |     ( 8 H X h x ê ÿ ¿ ╕ ╚ ╪ Φ ° |


9 |     ) 9 I Y i y ë Ö ⌐ ╣ ╔ ┘ Θ ∙ |
A |     * : J Z j z è Ü ¬ ║ ╩ ┌ Ω · |
B |     + ; K [ k { ï ¢ ½ ╗ ╦ █ δ √ |
C |     , < L \ l | î £ ¼ ╝ ╠ ▄ ∞ ⁿ |
D |     - = M ] m } ì ¥ ¡ ╜ ═ ▌ φ ² |
E |     . > N ^ n ~ Ä ₧ « ╛ ╬ ▐ ε ■ |
F |     / ? O _ o  Å ƒ » ┐ ╧ ▀ ∩   |
  +---------------------------------+

Note that I had to copy half of them and then the other half. Copy all of them at once and paste here did not seem to work for some reason (but it worked if I pasted into the DOSBox-X window). Similar for gedit - pasting in two steps seem to work here, but not one for all, or else it will print the log message "Error converting selection from UTF8_STRING" as you said. Not sure why.

**Comment by Wengier** [comment]
I have now added a new menu item "Stop clipboard pasting" to allow the users to stop the pasting in the middle while pasting long clipboard content. Because of this I have added a "Shared clipboard functions" for Linux SDL1 build too which will contain the items "Paste from the clipboard" along with this one.

**Comment by Wengier** [comment]
@rderooy I have improved the clipboard copy code, and it seems to work better this time - I can now copy the entire content of the chart from the DOSBox-X once this time:

    0 1 2 3 4 5 6 7 8 9 A B C D E F
  +---------------------------------+
0 |       0 @ P ` p Ç É á ░ └ ╨ α ≡ |
1 |     ! 1 A Q a q ü æ í ▒ ┴ ╤ ß ± |
2 |     " 2 B R b r é Æ ó ▓ ┬ ╥ Γ ≥ |
3 |     # 3 C S c s â ô ú │ ├ ╙ π ≤ |
4 |     $ 4 D T d t ä ö ñ ┤ ─ ╘ Σ ⌠ |
5 |     % 5 E U e u à ò Ñ ╡ ┼ ╒ σ ⌡ |
6 |     & 6 F V f v å û ª ╢ ╞ ╓ µ ÷ |
7 |     ' 7 G W g w ç ù º ╖ ╟ ╫ τ ≈ |
8 |     ( 8 H X h x ê ÿ ¿ ╕ ╚ ╪ Φ ° |
9 |     ) 9 I Y i y ë Ö ⌐ ╣ ╔ ┘ Θ ∙ |
A |     * : J Z j z è Ü ¬ ║ ╩ ┌ Ω · |
B |     + ; K [ k { ï ¢ ½ ╗ ╦ █ δ √ |
C |     , < L \ l | î £ ¼ ╝ ╠ ▄ ∞ ⁿ |
D |     - = M ] m } ì ¥ ¡ ╜ ═ ▌ φ ² |
E |     . > N ^ n ~ Ä ₧ « ╛ ╬ ▐ ε ■ |
F |     / ? O _ o  Å ƒ » ┐ ╧ ▀ ∩   |
  +---------------------------------+ 

Please check it out.

**Comment by rderooy** [comment]
@Wengier I had a moment to try it, and can confirm that it now works fine, at least with CP437.

**Comment by Wengier** [comment]
@rderooy Glad to hear that. I have also added a menu item “Copy all text in the screen" in the menu group to copy all screen text to the clipboard, and in such case there is no need to select the text.

**Comment by Wengier** [comment]
I have now added default shortcuts HOST(F11/F12)+A and HOST(F11/F12)+V to copy all text on the DOS screen to the clipboard and to paste text to the DOS screen respectively.

**Comment by Wengier** [comment]
@Carpintonto The official DOSBox-X version 0.83.7 that has support for the feature is now released. You can get the official Linux Flatpak from https://flathub.org/apps/details/com.dosbox_x.DOSBox-X

Thanks a lot for encouraging me to add support this feature for Linux too! Feel free to let me know if you find any issues.
