### ISSUE TITLE
MODE CON COLS=132 causes screen disruption

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2012]
Wengier's terrific work recently included a new MODE command that lets cols to 80 or 132 and lines to 25, 43, 50, or 60.

If you enter 

MODE CON COLS=132 LINES=43,

the screen gets confused with the prompt seeming to appear twice, and the activel prompt appearing in the right half of the window. A "cls" command doesn't solve the problem. (I tested with output=ttf.)

This is probably easy to fix. Meanwhile, many thanks for these excellent new features.

**Comment by Wengier** [comment]
@emendelson Thanks for reporting the issue! I think I have already fixed it, and you can download the latest Windows binary from:

* [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

It also adds support for the 512-character font as you request, along with enabling the euro option to work with TTF output.

**Comment by emendelson** [comment]
@Wengier  - Thank you for these fast and effective fixes!

Two remaining issues with ttf output. The command

mode con lines=43 cols=80

produces an "invalid parameters" message.

And the command

mode con lines=60 cols=80

correctly switches the mode, but the prompt becomes invisible, at least on my system.

These are obviously very minor problems!

**Comment by rderooy** [comment]
@emendelson I can duplicate the error message with 43 lines here, but ``mode con lines=60 cols=80`` works just fine. The prompt remains visible. I tried with ``output=surface``, ``output=ttf`` and ``output=opengl``.

Can you perhaps try to start dosbox-x with the ``-defaultconf`` parameter to rule out some setting in your config file?

**Comment by emendelson** [comment]
@rderooy - Yes, with `-defaultconf`, I don't get the problem that I mentioned with `mode con lines=60 cols=80`. I'll try to narrow down what's going wrong in my configuration.

But, as you say, the invalid parameters still occurs with 43 lines. I can't figure out where in the code that setting should be...

**Comment by Wengier** [comment]
@emendelson The 80x43 mode was not previously supported, but I have already add supported for it in my PR and you can check out the updated Windows binary:

* [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

**Comment by emendelson** [comment]
@Wengier - Fixed; thank you!
