### ISSUE TITLE
DOSBox-X 0.83.8 2020-11-31 22:04 MacOS ARM Release Build - Damaged?

### ISSUE THREAD

**Issue by Purduecoz** [joncampbell123/dosbox-x#2124]
I'm getting an error when trying to run both the SDL and SDL2 builds of the release version of DOSBox for MacOS ARM that they are damaged.  Right clicking and choosing Open continues to result in the same error.  I've used multiple browsers with the same result.  The Intel versions run fine, but obviously I'd prefer to use the ARM versions if at all possible.

Thank you!

**Comment by joncampbell123** [comment]
If you run them directly from Terminal, do they work?

This might be Gatekeeper at work, I don't have an Apple signing certificate.

**Comment by Purduecoz** [comment]
> If you run them directly from Terminal, do they work?
> 
> This might be Gatekeeper at work, I don't have an Apple signing certificate.
> 
> If you look directly in the .app bundle, there is a dosbox-x executable you should be able to run directly.

They do the same thing directly from the Terminal.  Usually with Gatekeeper it'll complain about the app not being signed.  I don't get that here.  MacOS raises a window that says "dosbox-x is damaged and can't be opened.  You should move it to the trash."  My only options are to cancel or to move it to the trash.

**Comment by joncampbell123** [comment]
Anything on the terminal about *what* is damaged? Surely it provides some kind of error message on the Terminal about *what* is wrong.

Or am I just supposed to guess what is wrong while Mac OS X says DUH SOMETHING WRONG without an explanation.

If Apple is going to treat my .app bundle like dangerous nuclear waste, I at least want an explanation.

**Comment by Purduecoz** [comment]
Unfortunately nothing on the command line.  Just this pop up window that gives no additional detail. I don’t know enough about MacOS’s underpinnings to know if a log of such issues is kept somewhere. I can do some research.  Weird that the Intel version is just fine.

**Comment by joncampbell123** [comment]
Also, objdump cannot read Mach-O arm64 binaries *despite* running on an arm64 system????????

**Comment by joncampbell123** [comment]
I can't get Gatekeeper to do the same thing on my Macbook.

Can you see if the Console app shows anything about what is wrong?

https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/

**Comment by Purduecoz** [comment]
> I can't get Gatekeeper to do the same thing on my Macbook.
> 
> Can you see if the Console app shows anything about what is wrong?
> 
> https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/

Unfortunately, Console shows a very non-specific error about Gatekeeper:

Dec 27 10:55:31 Chriss-MacBook-Air-M1 com.apple.xpc.launchd[1] (application.com.hackipedia.DOSBoxX.2186918.2186921[11964]): removing service since it exited with consistent failure - OS_REASON_EXEC | Gatekeeper policy blocked execution

I'm seeing a lot of folks reporting that Big Sur's Gatekeeper is blocking things that were not blocked on Catalina.  I wish I knew how to see what the specific policy is that DOSBox is running "afoul" of.

**Comment by joncampbell123** [comment]
At this point I'm guessing maybe it has "naughty" language in the info plist?

Can't talk about "hacking" after all. :shrug:

**Comment by Purduecoz** [comment]
Wouldn't the Intel version have the same language in the plist?

**Comment by joncampbell123** [comment]
The same plist is used in both builds, so I'm not sure why the Intel platforms are OK with that, and arm64 ones are not...

In any case, I pushed a commit that changes the identifier, not only to try to evade this issue, but also because I haven't used Hackipedia to publish DOSBox-X since moving to GitHub in 2012 anyway.

**Comment by Purduecoz** [comment]
That fixed it.  Absolutely unbelievable.  Thanks!

**Comment by joncampbell123** [comment]
Really?!?!? :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: 

So what other naughty words am I not allowed to use there? Does the F-word trigger Gatekeeper too? :rofl: :rofl:

**Comment by Purduecoz** [comment]
Doesn't seem to based on my testing, unless now that it's got an exception it just isn't checking it any longer!

**Comment by Purduecoz** [comment]
Wait, I'm incorrect.. I accidentally ran the x86_64 version.  Changing the plist doesn't seem to have worked around Gatekeeper.  Still saying corrupt.

**Comment by joncampbell123** [comment]
Running x86_64 builds on the ARM macbook from the Terminal, it's showing that the FFMPEG libraries it links to are not entirely there, so in that case, it is "corrupt".

I think it's time for Mac OS builds to remove FFMPEG support anyway (compile with --disable-avcodec) and to stop packing dylib files in the .app bundle.

Maybe in the future if people need FFMPEG MPEG-TS capture I could arrange to put the FFMPEG and libx264 libraries in-tree as part of the build.

**Comment by Purduecoz** [comment]
I had been working with the version that's on the website.  Think there'd be any different result if I grabbed the source and compiled in Xcode?

**Comment by joncampbell123** [comment]
Perhaps. I'm fixing a bug with --disable-avcodec right now.

**Comment by joncampbell123** [comment]
Done. --disable-avcodec was enabling avcodec. configure.ac needs to use $enableval not assume 'yes'

**Comment by Purduecoz** [comment]
Interesting - potential root cause? https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/

Looks like all code on Apple Silicon requires *some* kind of signature, even if not a developer signature.

**Comment by joncampbell123** [comment]
Maybe, but using the standard ld/clang tools gets ad-hoc signing anyway, and that is what DOSBox-X does to build itself.

**Comment by Skaggynuts** [comment]
Big Sur on M1 won't let you run any unsigned code by default, but there is a way around it.

From the terminal run: sudo spctl --master-disable

Then you should be able to open DosBox

run sudo spctl --master-enable

to re-enable gatekeeper, you'll still be able to run DosBox, but you'll have to disable it again for the next unsigned program you want to run.

**Comment by Purduecoz** [comment]
> Big Sur on M1 won't let you run any unsigned code by default, but there is a way around it.

Thank you!  I was looking for a way to do exactly this.

**Comment by Purduecoz** [comment]
Hm.  Running the sudo spctl --master-disable resulted in the following (and still cannot execute DosBox):

dosbox-x-sdl2 % sudo spctl --master-disable
Password:
objc[27189]: Class SPExecutionPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class AppWrapper is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class AppWrapperPolicyResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class AppWrapperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class SPLog is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class MIS is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class SPExecutionHistoryItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class SPExecutionPolicyItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class SPDeveloperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[27189]: Class GKScanResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.

**Comment by Skaggynuts** [comment]
Okay I just did a fresh install, I had forgotten you also need to disable SIP from the recovery console.

1. Shutdown the system
2. Hold the power button until it says 'Loading Startup Options'
3. Hit Conintue under Options
4. Login with your user name / password
5. from Utilities open a terminal
6. type the command: csrutil disable
7. Restart

Don't download anything shady with Gatekeeper or SIP disabled, you can re-enable both of them once you successfully launch DosBox. If you run iOS apps they won't launch with SIP disabled.

**Comment by joncampbell123** [comment]
Whoah, hold on... I was under the impression Gatekeeper was supposed to ask the user first whether they wanted to run an unsigned application, I don't think you need to disable SIP to do that!

I *think* I fixed the "corrupt app" issue by changing the identifier in the plist, unless "dosbox-x" is another word on Gatekeeper's naughty language list.

**Comment by joncampbell123** [comment]
@Purduecoz For some odd reason, running "git", "clang", and "ld" the first time also produces those messages, but "git" does work despite that.

**Comment by Purduecoz** [comment]
The problem I’m having though is that gatekeeper isn’t just complaining about the app being downloaded from the Internet and still giving me an open option. It’s saying the app is corrupted and not providing an option to open at all. The plist identifier change didn’t fix it for me. I can try grabbing the source and compiling - I’ve been using the version posted on the website. Are you testing on an M1 ARM based Mac?  Thanks again.

**Comment by Skaggynuts** [comment]
FFMPEG really had nothing to do with it, I had it running fine before you had removed it. It's just apple making it really difficult for the user to run unsigned code on the M1 mac. To get the ARM version running I have to disable both Gatekeeper and System Integrity Protection.

**Comment by Purduecoz** [comment]
Same here. FFMPEG support didn’t seem to be causing me any issues with the x86_64 build on the M1 Mac.

**Comment by Skaggynuts** [comment]
Here's the steps I have to take if you want to see it for yourself.
https://www.youtube.com/watch?v=PS7yBHfhgRc

**Comment by mikeypdev** [comment]
Try this command on doxbox-x.app:

` xattr -cr dosbox-x.app`

It basically removes the quarantine attribute from the downloaded files. You should not need to disable gatekeeper or use csrtool. *works on my machine*

**Comment by Purduecoz** [comment]
> ` xattr -cr dosbox-x.app`

Worked great on mine too.  Thank you!

**Comment by ksbex** [comment]
I also was able to launch the app using "xattr -cr dosbox-x.app"

**Comment by hiatsu0** [comment]
Confirmed, got it working simply by issuing the xattr command!

Should have guessed that was required as all .ipa files downloaded outside the Store need that to run too.

**Comment by neonblurb** [comment]
I found this worked for the latest build as of now also, 0.83.11 downloaded via: https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.11/dosbox-x-macosx-arm64-20210301003750.zip has the same issue (and the same fix!)

**Comment by Steuard** [comment]
I'm seriously uncomfortable telling people (even experts, really, but especially ordinary users) to disable the quarantine features in MacOS to install software. Gatekeeper exists for awfully good reasons! Just about every program I use has at least enough basic signing or whatever that I can run it at least with a "control-click: open". I don't want to train myself or anyone else to ignore that. If this is just a requirement of a very basic level of code signing (I think it's fine to be an "unidentified developer"), isn't that built in to most modern build tools at this point? Maybe it's more complex than I recognize, but it would be really good to find a way to avoid this level of circumvention of Gatekeeper.
