### ISSUE TITLE
Add translation options in the main installer

### ISSUE THREAD

**Issue by Dalekamistoso** [joncampbell123/dosbox-x#2326]
Hi!

I would like to suggest the following changes for improving multilanguage funcionality:

Installer under Windows plataforms:

Adding an extra item on custom installation for install the extra translations folder something like "Install available translations" or somewhat.

Adding an extra configuration screen in the main installer for choosing default menu language reading the available .lng files and change the default .conf file or install a previously modified one with the default value for selected language.

Under linux:

Would be enough adding the files to the flatpak package and a little bash script named "dosbox-x-lang.sh" or equivalent that copies a default .conf file or simply change the language=xxx.lng text value in the the config file, this could be done using sed.

Or simply install translations folder by default under installation folder because at least in windows those files are note installed.

This would increase and improve functionality and configuration during and after installation

Thanks in advance

**Comment by Wengier** [comment]
Thanks for suggesting the option to install extra translations! It will certainly help improve the multi-language functionality. On the other hand, in the translations folder there are currently only English and Spanish translations. I hope there will be more translations to be included for this.

P.S. There are some updates to the user interface in the latest DOSBox-X 0.83.11 version. Can you check the current Spanish translation file and update it if necessary? Thanks.

**Comment by Dalekamistoso** [comment]
Hi Wengler!

Thanks for your response!

My intention from the beginning is encouraging people to add so many languages as possible,  so I hope that people after seeing that extra languages are available in the installer be encouraged to add their own language (many people not even know that this option exists).

The next language I want to add if possible is croatian, in fact I pretend to convince a croatian friend that collaborated with me recently with the translation of another program (Lunar IPS) to help me with DosBox-X translation to his language (he has no programming skills so I will have to deal with the work with his guidance so it will take a time).

Regarding other languages, currently I only speak english, spanish and a basic german, so I don´t even dare to make a low quality german translation or germans guys will kill me ;)

Regarding to the recent changes, I will check those this weekend or the next one, thanks for your notice!.


Kind Regards

**Comment by Dalekamistoso** [comment]
Hi again :)

I had an unexpected spare time so I updated the files as you requested and I already have added the corresponding pull request (#2330).

With that pull request the translation is already updated and now conformed to the changes in the new version.

So, you can resume your work with my proposal if you wish.

Thanks.

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for the update. I would hope to see other language translations too.

**Comment by Wengier** [comment]
@Dalekamistoso With the latest code DOSBox-X now supports saving to and loading from UTF-8 encoded language files, and with this I think you can now use a single (UTF-8 encoded) language file for both Windows SDL1 and SDL2 builds, and just set ``country=34,858`` in [config] section of dosbox-x.conf for the Spanish language so that diacritics will appear in both builds. Below are MinGW SDL1 and SDL2 builds based on the latest code for testing:

* MinGW SDL1 build: [dosbox-x-mingw64.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64.zip)
* MinGW SDL2 build: [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)

Can you check it out and update the Spanish language file accordingly? Note that the welcome banner messages have also been reorganized so that translating them from stretch should be easier than before (and more compatible with other code pages too), but for the existing language file(s) you can manually copy the old translated text for the welcome banner messages. Thanks!

**Comment by Dalekamistoso** [comment]
Thanks you @Wengier,  I understand this is an UTF-8 codification (without bom) using DOS ASCII charset.

I will check it, adapt the changes and I will translate accordingly to it as soon as possible (I have to update structure too to keep in sync with latest changes).

Please, have a little patience and give me a few days I am still not at 100% due to an accident a few weeks ago.

**Comment by Dalekamistoso** [comment]
I have completed the translation and created a pull request in order to update it to keep in sync with current version.

But I found a bug when selecting PC98 japanese machines (all of them) if used along the active translation.

It mess up the texts inside the box and also breaks the special charset in drop-down menus and only works properly in default english mode.

I think that broken welcome message/intro manual could be related with escape codes, because those are not processed properly in PC98 mode.

I suggest one of these solutions:

* Not applying language translation to PC 98 mode and use the translation only for drop-down menus 
* Change the way that PC98 mode processes escape codes on non US languagesforce

I attach screenshots of this issue in order to help clarifying this bug (this happens with other output modes too)

![pc98_sdl2_eng](https://user-images.githubusercontent.com/67012746/118675603-03998880-b7fb-11eb-8829-40aeb43cc46c.png)
![pc98_sdl1](https://user-images.githubusercontent.com/67012746/118675607-04321f00-b7fb-11eb-86a8-2b86c3196795.png)
![pc98_sdl2](https://user-images.githubusercontent.com/67012746/118675608-04321f00-b7fb-11eb-81b4-358607694e5a.png)

**Comment by joncampbell123** [comment]
The problem with the welcome text is that it uses the proprietary box characters defined by NEC that don't follow standard Shift-JIS. GNU iconv won't support them either.

Perhaps the message text could support a prefix or alternate value that contains exactly the translated text to provide to the guest.

Another option could be to replace the border with a solid box or half box char to make a thicker border using characters that DO translate from UTF-8 to Shift-JIS.

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for reporting the issue with PC-98 mode. I have fixed _most_ of said issues in #2537, so please check out the updated builds below:

* Visual Studio SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Visual Studio SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

@joncampbell123 The issue with the border of the welcome banner was fixed about two days ago to allow CJK message translations, by separating the message text from the borders. But prior to the code in #2537, there were still two problems: 1. the messages of both PC-98 and non-PC-98 machine types use the same message identifiers, thus will mess up either other for the translation. 2. The codepage for the PC-98 mode is fixed to be 932, which prevented proper conversions between the code page and Unicode. #2537 fixes issue 1 completely and issue 2 partially. The end result should be much better than before.

**Comment by Dalekamistoso** [comment]
I have already uploaded the modifications and I have tested that translation text works properly (obviously non supported characters by PC98 will not show up properly, real machines works the same)

Also I translated the texts in the new specific machines labels .

I attach a screenshot to show the fix for PC98 working nicely :)

![dosbox-x-pc98](https://user-images.githubusercontent.com/67012746/118896079-af2fff00-b907-11eb-8df7-e129456ceb5b.png)

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for the updated language files. I just removed one duplicated line in the welcome message in standard mode, as there is now a new label named "SHELL_STARTUP_EXAMPLE", separated from "SHELL_STARTUP_TEXT1".

**Comment by Dalekamistoso** [comment]
Thanks  @Wengier I already supposed it was somekind of test label but I translated anyway because I didn´t want to break the consistency of the code.

I will update my files with the ones you have already modified :)

Also I have found today that new debug label menu item cannot be translated:

:MENU:HelpDebugMenu
Depurador

And still shows "Debug" untranslated (the options depending of it works as intended but not the main menu item text)


Thanks in advance :)

**Comment by Wengier** [comment]
@Dalekamistoso For the debugging builds, there is a new label called ":MENU:DebugMenu" which will allow you translate text of the "Debug" menu as a top-level menu. The original ":MENU:HelpDebugMenu" label is for translating the "Debugging options" submenu in the "Help" menu for non-debuging build. You can put both if you want of course. Hope this helps.

**Comment by Wengier** [comment]
@Dalekamistoso I have been doing language translation myself (for another language) and found some small issues during the translation, so I updated the code accordingly. Please check out the latest Windows build below. Thanks!

* Visual Studio SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

P.S. The current Spanish language file (partially but not yet fully updated to the latest) is available from:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/es/es_ES.lng

**Comment by Dalekamistoso** [comment]
I am happy to see that simplified chinese translation has been added to DosBoX-X , this can increase the numbers of users using the emulator.

It would be enough to translate the dropdown menus and intro text to be accepted a translation?

I ask this because it would take me far less time to do add this kind of translations and it would be easier to convince some friends and collaborators in some of my projects from other countries to help me translating.

I could make a basic german translation but a dude (he is not a programmer but works on IT) helped me in the past when I added croatian language to Lunar IPS.

Also another friend of me from Italy that has a very solid programming skills and I collaborate with him in some MSX projects.

I could convice him to add an italian translation if he only have to translat only a bunch of label text values than a massive translation..

In both cases which codes should I use for DosBox?

that is not a programmer when I released my second translation of Lunar IPS

**Comment by Wengier** [comment]
@Dalekamistoso There are different parts for text translations in the language file(s), such as:

1. Text in the drop-down menus.
2. Introduction text;
3. Error messages in the shell;
4. Short help messages for different DOS commands;
5. Long help messages for different DOS commands.

By now I have already translated text in parts 1-4 completely, and part 5 partially. There are still long help messages for certain commands remaining untranslated, but virtually all other messages did get translated already. I did not translate all of them in one day, but steps by steps, but I believe the translation has certainly reached a stage to be fully usable. Similarly, I think you can certainly try to convince your friends to translate text into other languages too. They don't have to be 100% translated all at once, but I think should be fine as long as they are good enough (c.f. parts 1-4), and they can fully translate the remaining text when they have time. Note that even when Microsoft released some language versions of DOS/Windows they did not fully translated text in the system either, but they are already good enough to be fully usable. So I think perhaps we can adopt the similar standards here too. Thanks for your support.

**Comment by Wengier** [comment]
@Dalekamistoso The latest Windows SDL1 build (which includes some small fixes for the language feature) is available below:

* Visual Studio SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

All existing language files have been updated accordingly as well. And the language file for code page 936 can be considered complete by now.

**Comment by Dalekamistoso** [comment]
@Wengier I would like to add a comment to your modification

In spanish we open the exclamated sentences with a "¡" symbol and close it with "!" because the 99.9% of words are vocally pronounced in the exact way as written and sentences are understood in the same order as written 100% so those characters are important to properly pronounce and emphatyse the content and circunstances that text describes in which are envolved (this applies to question marks as "¿" and "?").

I understand you probably deleted that symbol in order to not spoil welcome screen in japanese mode due to its obvious lack of proper characters (pc98 by example)

So I was thinking about removing the closing exclamation symbol "!" but it sounds a bit dull in spanish so I left it untouched without the opening "¡" as a minor grammatical error (as you left it).

I am mentioning it because if somebody complains about it instead to me, you have a detailed explanation of it and redirect those complains to me.

Also I have changed a couple of words in japanese welcome screen in order to improve its readability using only english characters.

Thanks again :)

**Comment by Dalekamistoso** [comment]
@Wengier relating to "which codes should I use for DosBox". 

I mean that you, for example, in my case, you specified me that the "country" value in "dosbox.conf" file (in the case of spanish language by example) had to be set to "country=34,848" but in the specification inside the .lng file you see:

:DOSBOX-X:VERSION:0.83.14
:DOSBOX-X:LANGUAGE:Spanish
:DOSBOX-X:CODEPAGE:858
:DOSBOX-X:REMARK:

So I propose you adding a label with the numerical value of the country (Spain=34 in this case) with a added label like:

:DOSBOX-X:COUNTRYCODE:034

In other words, not only the name of the language, because there are linguistical variations (grammatic/words) for large languages.

For example UK English / US English, both have the same codification and are the same language but there are words like color (US English) and colours (UK English), this can be a source of issues specially for eastern languages.

For example Mandarin chinese, Cantonese chinese, etc...

At this moment is not a problem, but if we intend to automatize this setting in the future (for adding dinamically new languages) using a menu item in the drop down menus probably we will have to read the settings from the labels specified above.

I know that it's supposed that you already know the code of your own country, but you know, unexperienced users does not usually get those minor details.

I hope that I clarified myself with this explanation and I hope that my proposal can also improve these translations :)

**Comment by Wengier** [comment]
@Dalekamistoso I did have a very basic knowledge of the Spanish language and understood that in Spanish exclamated sentences are opened with a "¡" symbol and closed with "!" (similar for "¿" and "?" for question marks). But I did not really remember that I removed any such symbols in the Spanish language file. Your previous Spanish language file is still accessible from here:

https://raw.githubusercontent.com/Dalekamistoso/dosbox-x/f79850503560141bdb774aa59b85a29ef4da5be2/contrib/translations/es/es_ES.lng

And the Spanish language file in the current repository is here:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/es/es_ES.lng

I don't think there is any change related to such symbols between them. Perhaps you can check it again?

**Comment by Wengier** [comment]
@Dalekamistoso The reason I added a :DOSBOX-X:CODEPAGE label in the language file(s) is that some users may not (or forget to ) set the COUNTRY setting in the config file, and if there is no such label then the displayed text for the translated labels will become a mess. With a :DOSBOX-X:CODEPAGE label added DOSBox-X will use the saved code page for the UTF-8 => code page conversion. But this saved code page does not automatically set the DOS code page inside DOSBox-X. It is solely for the purposes of decoding languages files. On the other hand, you still set the DOS code page inside DOSBox-X using CHCP or KEYB command.

Meanwhile, the country code is useful for date/time formats inside DOSBox-X, but it is not useful for decoding the language file itself. So saving the country code inside the language file won't actually have any effect (you still need to set the country code inside DOSBox-X using another config setting anyway). I understand what you say about UK English / US English, etc, but this is an issue with language descriptions rather than country codes. So instead of setting the country codes in the language files, we can expand the language names themselves, e.g.

:DOSBOX-X:LANGUAGE:English (United States)

vs

:DOSBOX-X:LANGUAGE:English (United Kingdom)

P.S. Mandarin Chinese and Cantonese Chinese etc are spoken languages and generally not considered written languages. The written forms of the Chinese language are usually either Simplified Chinese or Traditional Chinese. So in such cases we have:

:DOSBOX-X:LANGUAGE:Simplified Chinese

vs

:DOSBOX-X:LANGUAGE:Traditional Chinese

If want to remind the users the codes of their countries as you said, we can also add them using the :DOSBOX-X:REMARK: label.

Hope this helps.

**Comment by Wengier** [comment]
@Dalekamistoso I want to mention that there are also new labels including :DRIVE, :TYPE, :LABEL, :DRIVE_NUMBER, :DISK_NAME, :IDE_POSITION, and :SWAP_SLOT since the previous build. They are already in en_US.lng and zh_cn.lng; can you add them to es_ES.lng too? Thanks.

**Comment by Dalekamistoso** [comment]
> @Dalekamistoso I want to mention that there are also new labels including :DRIVE, :TYPE, :LABEL, :DRIVE_NUMBER, :DISK_NAME, :IDE_POSITION, and :SWAP_SLOT since the previous build. They are already in en_US.lng and zh_cn.lng (very easy to find them since they are almost on the top of the language files); can you add them to es_ES.lng too? Thanks.

No problem I will check today :)

**Comment by Dalekamistoso** [comment]
Everything updated, also I have added a couple of cosmetic changes in help texts of two commands

**Comment by Wengier** [comment]
@Dalekamistoso The feature to launch host programs to run on the host systems is no longer limited to Windows, so I renamed the menu text from "Windows host applications" to "Host system applications". And I wonder if "Aplicaciones de host" is the correct Spanish translation for it? And the help message for `MOUNT -pr` is added to the output of `MOUNT /?`, so I want to confirm if "Ruta es relativa a la ubicación del archivo de configuración" is the correct translation for the message "Specify the path is relative to the config file location"? Thanks.

**Comment by Dalekamistoso** [comment]
Before directly answering your question I would like to clarify a couple of concepts so you can understand better the choices taken in translation so you can properly understand my approach.

In first place I would like to note that from a purely linguistical point of view the correct translation is "Aplicaciones de anfitrión" (host=anfitrión).

Due to space limitations in Welcome text I had to keep word "host" (english term) so in order to keep a consistency in the terminology used in drop down menus and welcome message I decided to take the same approach as VirtualBox so I decided to change it to "Aplicaciones de Host".

And now I will reply your questions:

Why I used: "Aplicaciones de host" <-(host applications) 

Instead of the exact translation: "Aplicaciones de anfitrión de Windows" <-(Windows host applications)

I have been watching the development of DosBox-X related to the functionality of this menu item so I decided going a bit in advance and keep a "neutral host" approach for the last builds (which approach did you took with simplified chinese?).


Regarding to the extra -pr help line you have added, the exact translation for:

"Specify the path is relative to the config file location" 

is:

"Especifica que la ruta es relativa a la ubicación del archivo de configuración"

I think that this exact translation will overflow the line so it will be better that I will change myself the text and adjust the lines so I would translate as something shorter:

"Indica que la ruta es relativa a la ubicación del archivo config"

I will check the new messages.txt and add the proper help line for it along the day 

There is something more that I should add?

Also there is a couple of things I would like to change in the translated texts under debug menu options because I don´t know how to describe it in spanish without seeming weird (some technological texts are a bit weird in spanish form so I am looking a few more friendly synonyms).

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for the explanation. I think even "Indica que la ruta es relativa a la ubicación del archivo config" may overflow that line, so I wonder if there is any way to make it even shorter?

There are indeed small additions in the updated DOSBox-X build I uploaded above, including "TTF word processor: FastEdit", which I added myself as "Procesador de texto TTF: FastEdit" in es_ES.lng (following other examples), and "DOSBox-X %s configuration directory" was changed to "DOSBox-X %s user configuration directory". There are some small adjustments in the help message of CONFIG command (type `CONFIG /?`) as well, which you can check out.

For "Windows host applications" to "Host system applications" change, in Simplified Chinese I just removed the "Windows" part, since the previous translation literally means "Windows host system applications", so deleting the word "Windows" should be okay in this case.

Please try the Windows build I posted above for latest messages. Thanks!

**Comment by Wengier** [comment]
@Dalekamistoso For space reasons I understand it may be perfectly fine to keep some English words as is during the translation, and this is the case for some other language files too (note that now there is also Japanese language file, available from https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/ja/ja_JP.lng). Since the sentence "Indica que la ruta es relativa a la ubicación del archivo config"" will slightly overflow, I removed the word "que" in the sentence to make it look better on the screen, even though it is definitely better to have this word in the sentence in all other cases. I have updated the Spanish language file slightly myself to save your time, but if you find any issue(s) please free feel to let me know. Thanks!

**Comment by Dalekamistoso** [comment]
Nice to see it attracks more people for translations take place, I asked publicly for help to see this happen (I have a bunch of japanese and korean developers following me at Twitter and I hoped that at least someboy spoke about it)!

Is very nice to see people adding translations and making more accesible this big project.

Regarding to your modification I have to correct it because it breaks the correct meaning of the whole sentence, I will download the update lng file and fix it today, and sorry for not answering before (health issues).

**Comment by Dalekamistoso** [comment]
@Wengier I have completed the changes and added a few touches to debug options.

Thanks again for your efforts 👍

**Comment by Wengier** [comment]
@Dalekamistoso I have certainly hoped to see Japanese, Korean and other language translations, so thanks a lot. I have updated the Spanish language file accordingly. Please do take good care of yourself. Thanks again.

**Comment by Wengier** [comment]
@Dalekamistoso I have added support for translations of the main Configuration Tool interface and added some new labels (such as :CONFIG_TOOL around the top) in the Spanish language file (https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/es/es_ES.lng) for the Configuration Tool text. Can you translate them to Spanish? Thanks. The updated Windows builds are available from:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Dalekamistoso** [comment]
As soon as I return home I'll do it!

**Comment by Dalekamistoso** [comment]
While updating the translation I found two bugs:

* If you translate any option under "Help" the close button remains untranslated (instead of "Cerrar" keeps "Close" in spanish):

![issue-02](https://user-images.githubusercontent.com/67012746/121815818-8c7bd680-cc78-11eb-96e4-4e1dcb07c9ee.png)
![issue-01](https://user-images.githubusercontent.com/67012746/121815819-8d146d00-cc78-11eb-9bbd-9f576b7a0ddb.png)

* I noticed that option texts with dots hardcoded cannot be deleted or displaced in order to properly fill the text buttons, those dots are fixed and crops the texts:

![issue-03](https://user-images.githubusercontent.com/67012746/121815871-ce0c8180-cc78-11eb-96de-684e0ef277d0.png)

Besides that it would be interesting in order to reduce the cost of updating the translations and for decreasing  the size of the code to reuse the very same variables from dropdown menus and adding only the non existent ones for configuration tool.

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for the updated translation! Yes, the 3 dots ("...") is hard-coded and is exactly for the purpose of reducing the cost of updating translations. By doing so, you only need to translate the text "Save" once, instead of twice for both "Save" and "Save...". But I see the button width does not fit your translation in this case, and I have enlarged the button width in the code accordingly. I have also fixed the issue that some "Close" button not showing "Cerrar".

Most labels in the Configuration Tool are new ones, so with few exceptions most existing labels from the drop-down menus cannot be reused for the Configuration Tool. However, I decided to significantly reduce the size of the language file by simplifying the translation of the "Drive" menu. So instead of translating menu text for each drive (A to Z), with the updated build you only need to translate it once for all drives. In any case, the updated Windows builds are available from:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Wengier** [comment]
@Dalekamistoso By now I have added the ability to translate the button names in the Mapper Editor interface, which is probably the last interface needing such support. In order to reduce the work to translate them, for most of them I decided to re-use the translated text from the drop-down menus. There are some remaining button names (along with some new title names) needed to be translated though. And because of the re-use of menu text, there may be some overflow text in some buttons, and probably you can fix them accordingly. If this is not possible, you can also manually add new mapper-specific labels (e.g. :MAPPER:caprawmidi) in the end of the language file so that these will be forced to be used instead of the text as used by the menu text. Please check out the updated Windows builds (same links as above). Thanks!

**Comment by Wengier** [comment]
@Dalekamistoso I have now re-used some drop-down menu labels (such as "Help" and "About DOSBox-X") for the Configuration Tool. Also enlarged the event buttons in the Mapper Editor. Please check out the latest Windows builds below:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

Thanks!

**Comment by Dalekamistoso** [comment]
@Wengier I have added the translation of the new labels I have a couple of cropped texts in mapper tool but it doesn't have too much importance because meaning is clear.

Also I found that HELP text button in configuration tool *seems* to be binded to HELP command so I propose a new label like:

:CONFIG_TOOL_HELP
Text that replaces "HELP" button in configuration tool
.

or something like

:HELP_BUTTON
Text that replaces "HELP" button in configuration tool
.

or:

 :HELP2
Text that replaces "HELP" button in configuration tool
.


Also I attach you a couple of screenshots for detailed info.

![16-06-21-issue-02](https://user-images.githubusercontent.com/67012746/122296611-e7246500-cefa-11eb-9e26-f5bdd7320c39.png)
![16-06-21-issue-01](https://user-images.githubusercontent.com/67012746/122296615-e7bcfb80-cefa-11eb-8a7e-c140d92edae9.png)


Thanks 👍

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for the updated translation! The :HELP label was removed in the previous build to use the "Help" text in the drop-down menu instead, but the "Help" button wasn't changed accordingly (thanks for letting me aware of this). For now I will assume the the text "Help" in both the button and the menu will be translated the same (as demonstrated in all current translations), so I will re-use the "Help" text as in the menu for the button to reduce the cost of translation. If it later becomes apparent they can be translated differently in other languages then a separate label can be made. The links for the updated Windows builds are the same as before:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

Thanks again!

**Comment by Wengier** [comment]
There are now translations for almost all CJK languages, with the sole exception of Korean language. Relevant discussions can be found in #2554 and #2572. I hope the Korean language support can be further verified too.

**Comment by Wengier** [comment]
There is now a page in the Windows installer for selecting existing translations (for new installations) as you suggested in the OP. Meanwhile, for the Linux Flatpak, perhaps @rderooy can take a look at it.

**Comment by Dalekamistoso** [comment]
Hi @Wengier 

Glad to see it finally! 

I was about to start a separate installer script for translations so you saved me time, thank you very much for the update!

**Comment by Wengier** [comment]
Yes, it has been added thanks for your support. Hope to to see more selections though.

**Comment by rderooy** [comment]
@Wengier for both flatpak and RPM it would be best if ``make install`` would install the language files, similar to how glshaders are installed. So something like ``/usr/share/dosbox-x/i18n`` or ``/usr/share/dosbox-x/lang``

**Comment by Dalekamistoso** [comment]
@Wengier I support that approach too, also it would be easier for scripting (Something like the shell script I wrote for openMSX for linux)

I have plans (after refactoring the new version of my script for openMSX) for writing a script tool for novice linux users to install and compile the latest build of DosBox-X easily from github

For reference:
https://github.com/Dalekamistoso/openMSX-linux-launcher-compiler

**Comment by Wengier** [comment]
@rderooy Can you send or post the changes needed to achieve such result? Thanks.
