### ISSUE TITLE
How do I compile this on Raspberry Pi 4?

### ISSUE THREAD

**Issue by WhyIsntTouhouBuntuRealYet** [joncampbell123/dosbox-x#2594]
I'm running TwisterOS Lite on an RPI4 8GB model.
First: Which packages do I need to install first?
Second: How do I compile this?
And third: How can I set up an Automount for floppy disks and CDs?

*Thank*

**Comment by rderooy** [comment]
Please have a look at https://github.com/joncampbell123/dosbox-x/blob/master/README.source-code-description

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
This is what I got after I compiled.

make[3]: Leaving directory '/home/pi/dosbox-x/src/gui'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x'
make: *** [Makefile:333: all] Error 2

Granted, I did omit 2 of the required packages because apt couldn't find them.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
Can anyone link a precompiled lib?

**Comment by Wengier** [comment]
@WhyIsntTouhouBuntuReal At this time some headers are being fixed in the repository code, and I suggest you to build the DOSBox-X 0.83.14 release version. It is available from:

https://github.com/joncampbell123/dosbox-x/archive/refs/tags/dosbox-x-v0.83.14.tar.gz

Hope this helps.

**Comment by Wengier** [comment]
You can also run the pre-compiled Linux Flatpak package on your system. It is available from the homepage or release section.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
flathub doesn't work. is there a .deb package?

**Comment by Wengier** [comment]
@WhyIsntTouhouBuntuRealYet The header file issue is already fixed in the latest code, so you can try check out the most recent code and build again. At this time there are only RPM packages in addition to Flatpaks for Linux.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
Do I just do autogen and then configure?

**Comment by Wengier** [comment]
If you used `git clone` to get the repository code previously, then try `git pull`, then `make`. Hope this helps.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
make[3]: *** [Makefile:435: sdlmain.o] Error 1
make[3]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14/src/gui'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14'
make: *** [Makefile:333: all] Error 2

I think linux hates me.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
also...
error: Nothing matches com.dosbox_x.DOSBox-X in remote flathub

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
Yay, it works now.
I used the .zip file instead of the Git command.

**Comment by rderooy** [comment]
The flatpak package is only available for 64bit x86_64 and 64bit Arm (aarch64). The Pi4 is 64bit capable but most Pi distros are unfortunately still 32bit.

What does ``uname -a`` return?

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
Okay, now it's not compiling anymore.
compilation terminated.
make[4]: *** [Makefile:793: hardware.o] Error 1
make[4]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.15/src/hardware'
make[3]: *** [Makefile:815: all-recursive] Error 1
make[3]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.15/src/hardware'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.15/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.15'
make: *** [Makefile:333: all] Error 2

What does this mean? And how do I fix it?

**Comment by Wengier** [comment]
@WhyIsntTouhouBuntuRealYet Can you post the full error output including the line(s) causing errors? Thanks.

**Comment by WhyIsntTouhouBuntuRealYet** [comment]
Nevermind, I fixed it. I downloaded the dependent packages and followed MagPi's guide, and it worked.
Wish I could say the same about the mouse, but that's a different matter.

**Comment by Ultrahead** [comment]
> make[3]: *** [Makefile:435: sdlmain.o] Error 1 make[3]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14/src/gui' make[2]: *** [Makefile:529: all-recursive] Error 1 make[2]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14/src' make[1]: *** [Makefile:400: all-recursive] Error 1 make[1]: Leaving directory '/home/pi/dosbox-x-dosbox-x-v0.83.14' make: *** [Makefile:333: all] Error 2
> 
> I think linux hates me.

I know this is an old post, but I'm trying to compile the latest sources for an aarch64 -based Linux distro and I get that error with sdlmain.o. 

Also, checking the build scripts, there's none for Linux with arm64/aarch64. Only on the script for Mac this scenario is considered. 

Any help here to get a successful compilation would be much appreciated. Thanks

**Comment by joncampbell123** [comment]
I don't remember clearly, but several years back I used to compile and test DOSBox-X on a Raspberry Pi 3 and 4.

The README and configure scripts should make it clear what libraries are required.

Some cleanup is in progress at the time of this post that should also help clarify dependencies, and some of the in-source libraries will be replaced with standard ones i.e. libflac, libogg, libvorbis, etc.

**Comment by Ultrahead** [comment]
Ok then, I will pause and wait for that cleanup before retrying.

For compiling for the RPi4, do you remember which specific configure script you used? (because RPi4 is aarch64-based)

**Comment by joncampbell123** [comment]
> Ok then, I will pause and wait for that cleanup before retrying.
> 
> For compiling for the RPi4, do you remember which specific configure script you used? (because RPi4 is aarch64-based)

I wish I did, but no. I still have the RPI4 though, and an RPi5 as well, to start testing on again.

**Comment by joncampbell123** [comment]
> Ok then, I will pause and wait for that cleanup before retrying.
> 
> For compiling for the RPi4, do you remember which specific configure script you used? (because RPi4 is aarch64-based)

The cleanup will probably be ongoing for a month or more, but one of the first things to do during that cleanup is list the dependencies and that should allow you to compile sooner than that.

**Comment by maron2000** [comment]
Did you read the [Build instruction](https://github.com/joncampbell123/dosbox-x/blob/master/BUILD.md) included in the source code?
There are no specific scripts to build on Raspi.

**Comment by Ultrahead** [comment]
@joncampbell123 I managed to compile de project with Debian 11:11, which seems to be compatible with the target platform. Now, I'm getting the follow log with a Segmentation Fault:

```
LOG: Early LOG Init complete
LOG: DOSBox-X's working directory: /mnt/SDCARD/Emus/DOS/dosboxx/bin
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG:          0 DEBUG MISC:Logging init complete
LOG: DOSBox-X version 2025.01.01 Commit a2a3a71 (Linux SDL2 64-bit)
LOG:          0       MISC:Copyright 2011-2025 The DOSBox-X Team. Project maintainer: joncampbell123 (The Great Codeholio). DOSBox-X published under GNU GPL.
LOG:          0 DEBUG GUI:SDL 1.2.14 hack: SDL_DISABLE_LOCK_KEYS=1
LOG: Prevent capture: 0
sh: setterm: not found
LOG: SDL: version 2.26.5, Video mali, Audio alsa
LOG:          0       GUI:Press Ctrl-F10 to capture/release mouse, Alt-F10 for configuration.
LOG: Host keyboard layout is now  ()
LOG: Mapper keyboard layout is now  ()
LOG:          0 DEBUG MISC:Initializing SDL joystick subsystem...
LOG:          0 DEBUG MISC:SDL reports 1 joysticks
LOG:          0 DEBUG GUI:Starting GUI
LOG:          0 DEBUG GUI:This version compiled against SDL 2.x
LOG:          0 DEBUG GUI:SDL2 version 2.26.5
LOG: SDL2 reports desktop display mode 1280 x 720
LOG: The default output for the video system: opengl
LOG:          0 DEBUG MISC:Early init (renderer): xBRZ options
LOG: Could not initialize OpenGL, switching back to surface
LOG: Configured windowposition: -
LOG: SDL: Current window pixel format: SDL_PIXELFORMAT_RGBX8888
LOG: SDL: You are running in 24 bpp mode, this will slow down things!
Segmentation fault
```

Unfortunately, there is no other info that provides more details about the fault, but it is interesting that OpenGL couldn't be initialized. The platform counts with both OpenGL and Vulkan APIs. Is there any way to get more info on what could be happening here?

**Comment by joncampbell123** [comment]
"LOG: SDL: You are running in 24 bpp mode, this will slow down things!"

That's only the case I can think of here. Do you know how to use "gdb" to run DOSBox-X and backtrace on the fault?

I'll dig out a RPi and start testing on that again.

**Comment by Ultrahead** [comment]
Yes, I know. But won't be able to do it until the other weekend.

Also, I compiled the standard version (non-SDL2 one) and it seems to work. No segmentation fault. Rendering is failing but probably I will have to tweak some SDL parameters and exec args to make it fully work, but no crash.

But it will have to wait for week since I'm AFK, now.

**Comment by Ultrahead** [comment]
Sorry, I forgot to add the log I get when compiling the standard version

```
LOG: Early LOG Init complete
LOG: "" is not a valid value for variable: configuration tool theme.
It might now be reset to the default value: 
LOG: "" is not a valid value for variable: configuration tool theme.
It might now be reset to the default value: 
LOG: CONFIG: Loaded config file: //.config/dosbox-x/dosbox-x-2025.01.01.conf
LOG: DOSBox-X's working directory: /mnt/SDCARD/Emus/DOS/dosboxx/bin
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG:          0 DEBUG MISC:Logging init complete
LOG: DOSBox-X version 2025.01.01 Commit a2a3a71 (Linux SDL1 64-bit)
LOG:          0       MISC:Copyright 2011-2025 The DOSBox-X Team. Project maintainer: joncampbell123 (The Great Codeholio). DOSBox-X published under GNU GPL.
LOG:          0 DEBUG MISC:DOSBox-X CheckOS results: id=0 major=0 minor=0
LOG:          0 DEBUG GUI:SDL 1.2.14 hack: SDL_DISABLE_LOCK_KEYS=1
LOG: Prevent capture: 0
LOG: E_Exit: Can't init SDL Unable to open mouse
E_Exit: Can't init SDL Unable to open mouse

LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Oct 31 2021 19:44:11
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: loaded: libdrm.so.2
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Subtract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays  detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: Extension GL_OES_fragment_precision_high  detected and used
LIBGL: Extension GL_EXT_shader_texture_lod detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 15
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Max Color Attachments: 8 / Draw buffers: 8
LIBGL: Hardware vendor is Imagination Technologies
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: sRGB surface supported
LIBGL: EGLImage to Texture2D supported
LIBGL: EGLImage to RenderBuffer supported
LIBGL: Targeting OpenGL 2.1
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: FBO workaround for using binded texture enabled
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/mnt/SDCARD/Emus/DOS/dosboxx/bin
LIBGL: Shuting down
```

No crashes here but the app shuts down without showing anything.

**Comment by Ultrahead** [comment]
Is there any way to tell SDL to use one of the DPads of the joystick found as mouse in the config file? (ditto with buttons)

**Comment by Ultrahead** [comment]
Thanks for the link.

I tried to override the check by setting mouse=never on SDL's config file and it didn't work either. Same result: SDL won't start.

**Comment by Ultrahead** [comment]
@joncampbell123 what could make the emulator go "shutting down" after recognizing the current folder?

(please read the log [here](https://github.com/joncampbell123/dosbox-x/issues/2594#issuecomment-2629303042) )

**Comment by Ultrahead** [comment]
@joncampbell123 a/o anyone, is there any way to prevent the automatic "shutting down" there? (which has a typo due to a missing ```t``` since it reads ```shuting```)

**Comment by Ultrahead** [comment]
Good news. It ended up that for the SDL1 version I needed to enable the swap chain, so fulldouble must be set to true.

![Image](https://github.com/user-attachments/assets/8587dd26-8005-4ce2-8d38-e5df20dd6c70)

Now I need to make it recognize the virtual keyboard and set one of the DPads as mouse. And also to render it to Fullscreen (for some reason it capped itself to a lower viewport size).

The bad news @joncampbell123 is that the SDL2 version continues to trigger a segmentation fault.

**Comment by Ultrahead** [comment]
SDL2-based version is now also working on the device. It was a matter of finding the correct combination of values for the config parameters.

![Image](https://github.com/user-attachments/assets/7d419201-5aea-4a0d-9a21-99ffaeb76389)

@joncampbell123 For some weird reason the emulator cannot setup OpenGL so it gets back to surface output and the segmentation fault is avoided by manually setting the correct fullscreen resolution and video driver. A plus is also disregarding dpi for correct positioning on screen.
