### ISSUE TITLE
Red Storm Rising doesn't work in DOSBox-X

### ISSUE THREAD

**Issue by jez9999** [joncampbell123/dosbox-x#5774]
### Describe the bug

Running the Red Storm Rising executable simply clears the screen and the game doesn't run.

### Steps to reproduce the behaviour

1. Go to Red Storm Rising directory.
2. Run the main executable.

### Expected behavior

Game runs.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2024.07.01

### Used configuration

```ini

```

### Output log

```text

```

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
`loadfix` works fine.

<img width="642" height="452" alt="Image" src="https://github.com/user-attachments/assets/cc6c4a20-e204-44d5-bb3c-f60d5a66680b" />

<img width="642" height="452" alt="Image" src="https://github.com/user-attachments/assets/22a773a9-d731-42ba-a879-e90f366e1a77" />

**Comment by jez9999** [comment]
What do you mean by `loadfix`?

**Comment by jez9999** [comment]
Oh I see what you mean, yeah works with `loadfix` on mine too but how come it would work on DOSBox 0.74 and not DOSBox-X?  I don't need to use `loadfix` on the former.

**Comment by maron2000** [comment]
loadfix is a dos command which you can find the explanation in the MS-DOS users manual.
Depending on the memory map, sometimes you need it, while sometimes you don't.
I don't think the devs are really willing to research this in deep while this can be easily solved by `loadfix`.

**Comment by jez9999** [comment]
Fixed with `loadfix`.

**Comment by jez9999** [comment]
Actually, it is still broken with `loadfix`.  When you actually try to go into battle you get "Please insert disk A and press a key".

**Comment by maron2000** [comment]
I actually don't know how to play this game, but seems to succeed in sinking the enemy in training mode.
Do I need to go further to reproduce what you said?

<img width="640" height="400" alt="Image" src="https://github.com/user-attachments/assets/29286568-7280-459a-ba28-827bf7a339b5" />

**Comment by jez9999** [comment]
I think it's just in the WW3 scenario when you go in to fight a battle.  See the attached video.  This doesn't happen in DOSBox 0.74.

https://github.com/user-attachments/assets/f5505b9e-1479-48a5-a3ce-597332e7bd4c

**Comment by maron2000** [comment]
Maybe trying `a20gate off` before launching the game might help.

**Comment by jez9999** [comment]
Nope, still get the same error.

**Comment by maron2000** [comment]
That's too bad, 
Hope you can find a solution.

**Comment by maron2000** [comment]
This is how far I went.

https://github.com/user-attachments/assets/f7221720-f3ee-43a1-a603-9b9c20e2933c

**Comment by jez9999** [comment]
Weird.  Still, DOSBox-X must be doing something different to the original DOSBox.

**Comment by jez9999** [comment]
Interestingly mine works if I choose CGA or EGA so it must be causing the problem when it needs "disk A" for the extra graphics.  Could there be some difference with how DOSBox-X handles file system requests that causes the game not to notice the graphics files available?

**Comment by maron2000** [comment]
Same game worked as same on dosbox-staging, without `loadfix` or `a20gate off`.
I don't know how you can get your error.

<img width="1186" height="920" alt="Image" src="https://github.com/user-attachments/assets/0ee5980f-7622-4407-b15e-caf9dba5bc48" />

**Comment by jez9999** [comment]
Yeah, my version works on DOSBox staging.  It's just DOSBox-X where it fails.

**Comment by jez9999** [comment]
@maron2000  Can you give a file listing for your version of the game with each file's MD5 checksum?

**Comment by maron2000** [comment]
Sorry for the late reply. Don't know how to get the checksum but the listing may give you some idea.

```
2025/07/29  08:46    <DIR>          .
2025/07/30  09:30    <DIR>          ..
2025/07/29  08:46           347,341 ANIMS
2025/07/29  08:46            10,113 ASOUND.RSR
2025/07/29  08:46             5,100 BSOUND.RSR
2025/07/29  08:46             9,826 CGRAPHIC.RSR
2025/07/29  08:46             6,087 CPLAYER.RSR
2025/07/29  08:46             7,751 EGRAPHIC.RSR
2025/07/29  08:46             3,224 EPLAYER.RSR
2025/07/29  08:46             4,561 INSTALL.EXE
2025/07/29  08:46             4,972 ISOUND.RSR
2025/07/29  08:46             5,335 MGRAPHIC.RSR
2025/07/29  08:46             1,656 MISC.RSR
2025/07/29  08:46             2,029 MPLAYER.RSR
2025/07/29  08:46               657 READ.ME
2025/07/29  08:46            43,991 REDSTART.RSR
2025/07/29  08:46             2,317 REDSTORM.COM
2025/07/29  08:46            94,057 REDSTRAT.RSR
2025/07/29  08:46            86,543 REDTACT.RSR
2025/07/29  08:46                64 RSRLOADR
2025/07/29  08:46            40,456 STBASE.RSR
2025/07/29  08:46            10,793 SU.RSR
2025/07/29  08:46             6,177 TGRAPHIC.RSR
2025/07/29  08:46             2,460 TPLAYER.RSR
2025/07/29  08:46             5,903 TSOUND.RSR
```
